package personal.schedulingservice.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.*;
import personal.schedulingservice.util.FlightStatusConverter;


@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "ScheduledFlight")
public class ScheduledFlight {
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String flightId;

    @DynamoDBAttribute
    @DynamoDBTypeConverted(converter = FlightStatusConverter.class)
    private FlightStatus flightStatus;

    @DynamoDBAttribute
    private FlightEvent departure;

    @DynamoDBAttribute
    private FlightEvent arrival;

    @DynamoDBAttribute
    private String flightNumber;

    @DynamoDBAttribute
    private LiveFlightData liveFlightData;
}
